name: Create Release Zip

permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Zip Release
        uses: TheDoctor0/zip-release@0.7.6
        with:
          filename: denotest.zip

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./denotest.zip
          asset_name: denotest.zip
          asset_content_type: application/zip
          
